const translations = {
  en: {
    title: "MannMithra - News",
    navHome: "Home",
    navNews: "News",
    navSchemes: "Schemes",
    navGuide: "Guide",
    news1Title: "Latest Agricultural News",
    news1Content: "Stay Updated on Agricultural Trends and Updates",
    news2Title: "Weather Updates",
    news2Content: "Plan Better with Real-Time Weather Reports",
    news3Title: " Market Price Updates",
    news3Content: "Stay Informed About Crop Market Trends",
    news4Title: " Success Stories",
    news4Content: " Learn from Farmers Who Made a Difference",
    news5Title: " Events and Workshops",
    news5Content: "Stay Connected with Farming Events Near You",
    news6Title: " Policy and Government Announcements",
    news6Content: "Stay Informed About Policies Affecting Farmers",
    news7Title: " Expert Opinions and Advice",
    news7Content: "Get Professional Insights to Improve Your Farm",
    footerText: "&copy; 2025 Mannmithra. All rights reserved.",
    buttonText: "ஆங்கிலத்திற்கு மாறவும்",
    introText: "Agriculture is a dynamic field, with new policies, technological advancements, and challenges emerging regularly. This section provides you with the most recent news affecting the farming community in Tamil Nadu, India, and globally.",
    nationalNewsTitle: "National Agricultural News:",
    budgetNews: "Budget Increase for Agriculture: The Indian government plans to raise the agriculture sector budget by approximately 15% to about $20 billion in the upcoming fiscal year. This marks the most significant increase in over six years, aiming to support rural incomes and control inflation. The focus will be on high-yield seed varieties, improved storage and supply infrastructure, and enhanced production of pulses, oilseeds, vegetables, and dairy. The initiative also seeks to boost farm exports to $80 billion by 2030.",
    climateResilientSeeds: "Climate-Resilient Seeds Development: In response to climate change, Indian scientists are developing climate-resilient seed varieties that offer better yields with less water and enhanced disease resistance...",
    tamilNaduNewsTitle: "Tamil Nadu-Specific News:",
    organicFarmingPolicy: "Organic Farming Policy Unveiled: The Tamil Nadu government has introduced an organic farming policy aimed at promoting chemical-free agriculture...",
    farmerWelfareMeasures: "Farmer Welfare Measures: Over the past three years, the Tamil Nadu government has released ₹833.88 crore to support more than 11.95 lakh farmers affected by natural disasters...",
    globalTrendsTitle: "Global Agricultural Trends:",
    aiInAgriculture: "AI in Agriculture: Artificial Intelligence (AI) is playing a significant role in enhancing crop yields, managing water use more efficiently...",
    landConflicts: "Land Conflicts Affecting Renewable Energy Projects: In western India, the construction of a 100-megawatt solar plant by Tata Power in Maharashtra's Nandgaon has faced significant resistance from local farmers...",
    weatherIntro: "Weather plays a critical role in farming. With accurate forecasts, you can plan your activities, reduce risks, and ensure optimal crop health. Our weather update section offers insights tailored to your region.",
    dailyForecast: "Daily & Weekly Forecasts:",
    currentConditions: "Current Conditions: As of January 26, 2025, in Coimbatore, India, the weather is mostly cloudy with a temperature of 84°F (29°C).",
    upcomingForecast: "Upcoming Forecast:",
    forecastSunday: "Sunday, January 26: Clouds followed by a brightening sky, High: 92°F (33°C), Low: 65°F (18°C).",
    forecastMonday: "Monday, January 27: Nice with some sunshine, High: 88°F (31°C), Low: 66°F (19°C).",
    forecastTuesday: "Tuesday, January 28: Mostly sunny and pleasant, High: 87°F (31°C), Low: 67°F (20°C).",
    forecastWednesday: "Wednesday, January 29: Partly sunny and nice, High: 86°F (30°C), Low: 71°F (21°C).",
    forecastThursday: "Thursday, January 30: Partly sunny, High: 86°F (30°C), Low: 71°F (22°C).",
    forecastFriday: "Friday, January 31: Humid with clouds and sunshine; a couple of thunderstorms in the afternoon, High: 88°F (31°C), Low: 72°F (22°C).",
    forecastSaturday: "Saturday, February 01: Partly sunny and humid, High: 87°F (31°C), Low: 71°F (21°C).",
    extremeWeather: "Extreme Weather Alerts:",
    cycloneAlert: "Cyclone Michaung: Recently, Cyclone Michaung caused significant damage in certain regions. Farmers are advised to assess crop damage and report losses to local agricultural offices to avail relief assistance.",
    rainfallAlert: "Heavy Rainfall in Southern Districts: Torrential rains have affected the southern districts. It's crucial to monitor local advisories and take necessary precautions to protect crops and livestock.",
    seasonalWeather: "Seasonal Weather Trends:",
    monsoonPatterns: "Monsoon Patterns: The Northeast monsoon has been erratic, affecting sowing schedules. Farmers are encouraged to adopt flexible cropping strategies and consider short-duration crop varieties to mitigate potential losses.",
    temperatureFluctuations: "Temperature Variations: Unseasonal temperature fluctuations have been observed, which may impact crop growth stages. Implementing micro-irrigation and mulching can help manage soil temperature and moisture levels.",
  },
  ta: {
    title: "மண் மித்ரா - செய்திகள்",
    navHome: "முகப்பு",
    navNews: "செய்திகள்",
    navSchemes: "திட்டங்கள்",
    navGuide: "வழிகாட்டி",
    news1Title: "சமீபத்திய விவசாய செய்திகள்",
    news1Content: "விவசாயப் போக்குகள் மற்றும் புதுப்பிப்புகள் குறித்து புதுப்பித்த நிலையில் இருங்கள்",
    news2Title: "வானிலை புதுப்பிப்புகள்",
    news2Content: "நிகழ்நேர வானிலை அறிக்கைகளுடன் சிறப்பாக திட்டமிடுங்கள்",
    news3Title: " சந்தை விலை புதுப்பிப்புகள்",
    news3Content: "பயிர் சந்தை போக்குகள் பற்றி தொடர்ந்து தெரிந்து கொள்ளுங்கள்",
    news4Title: " வெற்றிக் கதைகள்",
    news4Content: " ஒரு வித்தியாசத்தை ஏற்படுத்திய விவசாயிகளிடமிருந்து கற்றுக்கொள்ளுங்கள்",
    news5Title: " நிகழ்வுகள் மற்றும் பட்டறைகள்",
    news5Content: "உங்களுக்கு அருகிலுள்ள விவசாய நிகழ்வுகளுடன் இணைந்திருங்கள்",
    news6Title: " கொள்கை மற்றும் அரசு அறிவிப்புகள்",
    news6Content: "விவசாயிகளை பாதிக்கும் கொள்கைகள் பற்றி தொடர்ந்து தெரிந்து கொள்ளுங்கள்",
    news7Title: " நிபுணர் கருத்துக்கள் மற்றும் ஆலோசனை",
    news7Content: "உங்கள் பண்ணையை மேம்படுத்த தொழில்முறை நுண்ணறிவுகளைப் பெறுங்கள்",
    footerText: "&copy; 2025 மண் மித்ரா. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
    buttonText: "Switch to English",
    introText: "விவசாயம் ஒரு அதிநவீன துறை...",
    nationalNewsTitle: "தேசிய விவசாய செய்திகள்:",
    budgetNews: "விவசாயத்திற்கு பட்ஜெட் அதிகரிப்பு...",
    climateResilientSeeds: "காலநிலை மாற்றத்திற்கேற்ப...",
    tamilNaduNewsTitle: "தமிழ்நாடு சார்ந்த செய்திகள்:",
    organicFarmingPolicy: "காரிக வணிக கொள்கை அறிமுகம்...",
    farmerWelfareMeasures: "விவசாயிகள் நலன் சார்ந்த நடவடிக்கைகள்...",
    globalTrendsTitle: "உலகளாவிய விவசாய போக்குகள்:",
    aiInAgriculture: "விவசாயத்தில் செயற்கை நுண்ணறிவு...",
    landConflicts: "பசுமை ஆற்றலின் நில மோதல்கள்...",
    weatherIntro: "விவசாயத்தில் வானிலை மிக முக்கியமான பங்கு வகிக்கிறது...",
    dailyForecast: "தினசரி மற்றும் வாராந்திர முன்னறிவிப்புகள்:",
    // Add Tamil translations for all sections...
  }
};

let currentLanguage = 'en';

const elements = {
  title: document.getElementById('title'),
  navHome: document.getElementById('navHome'),
  navNews: document.getElementById('navNews'),
  navSchemes: document.getElementById('navSchemes'),
  navGuide: document.getElementById('navGuide'),
  news1Title: document.getElementById('news1Title'),
  news1Content: document.getElementById('news1Content'),
  news2Title: document.getElementById('news2Title'),
  news2Content: document.getElementById('news2Content'),
  news3Title: document.getElementById('news3Title'),
  news3Content: document.getElementById('news3Content'),
  footerText: document.getElementById('footerText'),
  button: document.getElementById('languageToggle'),
  introText: document.getElementById('introText'),
  nationalNewsTitle: document.getElementById('nationalNewsTitle'),
  budgetNews: document.getElementById('budgetNews'),
  climateResilientSeeds: document.getElementById('climateResilientSeeds'),
  tamilNaduNewsTitle: document.getElementById('tamilNaduNewsTitle'),
  organicFarmingPolicy: document.getElementById('organicFarmingPolicy'),
  farmerWelfareMeasures: document.getElementById('farmerWelfareMeasures'),
  globalTrendsTitle: document.getElementById('globalTrendsTitle'),
  aiInAgriculture: document.getElementById('aiInAgriculture'),
  landConflicts: document.getElementById('landConflicts'),
  weatherIntro: document.getElementById("weatherIntro"),
  dailyForecast: document.getElementById("dailyForecast"),
  currentConditions: document.getElementById("currentConditions"),
  upcomingForecast: document.getElementById("upcomingForecast"),
  forecastSunday: document.getElementById("forecastSunday"),
  forecastMonday: document.getElementById("forecastMonday"),
  forecastTuesday: document.getElementById("forecastTuesday"),
  forecastWednesday: document.getElementById("forecastWednesday"),
  forecastThursday: document.getElementById("forecastThursday"),
  forecastFriday: document.getElementById("forecastFriday"),
  forecastSaturday: document.getElementById("forecastSaturday"),
  extremeWeather: document.getElementById("extremeWeather"),
  cycloneAlert: document.getElementById("cycloneAlert"),
  rainfallAlert: document.getElementById("rainfallAlert"),
  seasonalWeather: document.getElementById("seasonalWeather"),
  monsoonPatterns: document.getElementById("monsoonPatterns"),
  temperatureFluctuations: document.getElementById("temperatureFluctuations"),
  footerText: document.getElementById("footerText"),
  button: document.getElementById("languageToggle"),
};

document.getElementById('languageToggle').addEventListener('click', () => {
  currentLanguage = currentLanguage === 'en' ? 'ta' : 'en';
  Object.keys(elements).forEach(key => {
    if (key === 'button') {
        elements[key].textContent = translations[currentLanguage].buttonText;
    } else {
        elements[key].textContent = translations[currentLanguage][key];
    }
  });
});